namespace AccessManagement.Application.UseCases.ApprovalRoles.UpdateApprovalRole;

public interface IUpdateApprovalRoleUseCase : IUseCase<UpdateApprovalRoleUseCaseInput, UpdateApprovalRoleUseCaseOutput>;
