namespace AccessManagement.Application.UseCases.Users.AccountUsers.SetUserAccountProfiles;

public interface ISetUserAccountProfilesUseCase
  : IUseCase<SetUserAccountProfilesUseCaseInput, SetUserAccountProfilesUseCaseOutput>;
