namespace AccessManagement.Application.UseCases.Profiles.SetProfilePermissions;

public interface ISetProfilePermissionsUseCase
  : IUseCase<SetProfilePermissionsUseCaseInput, SetProfilePermissionsUseCaseOutput>;
