namespace AccessManagement.Application.UseCases.Users.AccountUsers.SetUserAccountActivation;

public interface ISetUserAccountActivationUseCase
  : IUseCase<SetUserAccountActivationUseCaseInput, SetUserAccountActivationUseCaseOutput>;
