<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>access-management-api-development</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
      <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AccessManagement.Application\AccessManagement.Application.csproj" />
      <ProjectReference Include="..\AccessManagement.Infrastructure\AccessManagement.Infrastructure.csproj" />
    </ItemGroup>

</Project>
