namespace AccessManagement.Application.UseCases.ApprovalRoles.SetApprovalRoleActivation;

public interface ISetApprovalRoleActivationUseCase
  : IUseCase<SetApprovalRoleActivationUseCaseInput, SetApprovalRoleActivationUseCaseOutput>;
