namespace AccessManagement.Application.UseCases.ApprovalRoles.ListApprovalRoles;

public interface IListApprovalRolesUseCase : IUseCase<ListApprovalRolesUseCaseInput, IReadOnlyCollection<ApprovalRoleOutput>>;
