namespace AccessManagement.Application.UseCases.Profiles.SetProfileActivation;

public interface ISetProfileActivationUseCase
  : IUseCase<SetProfileActivationUseCaseInput, SetProfileActivationUseCaseOutput>;
